import type { CefrLevel, LessonTemplate } from './types'

const createTemplate = (
  level: CefrLevel,
  sequence: number,
  grammarFocus: string,
  readingTaskType: LessonTemplate['readingTaskType'],
  writingTaskType: LessonTemplate['writingTaskType'],
  themePool: string[],
  targetWordRange: LessonTemplate['targetWordRange'],
  questionCounts: LessonTemplate['questionCounts'],
  teachingGoal?: string,
  targetSentences: string[] = [],
  reviewFocus: string[] = [],
): LessonTemplate => ({
  templateId: `${level}-${String(sequence).padStart(2, '0')}`,
  level,
  sequence,
  grammarFocus,
  readingTaskType,
  writingTaskType,
  themePool,
  teachingGoal,
  targetSentences,
  reviewFocus,
  targetWordRange,
  questionCounts,
})

export const lessonTemplatesByLevel: Record<CefrLevel, LessonTemplate[]> = {
  A1: [
    createTemplate(
      'A1',
      1,
      'alphabet_and_classroom_english',
      'reading_mcq',
      'short_paragraph',
      ['letters and sounds', 'classroom English', 'numbers and dates'],
      { min: 60, max: 100 },
      { reading: 3, grammar: 3 },
      '能听懂并说出课堂里最常用的英文指令、数字和日期。',
      ['How do you spell ...?', 'Can you repeat that?', 'It is number ...'],
      ['字母发音', '数字和日期', '课堂指令'],
    ),
    createTemplate(
      'A1',
      2,
      'be_and_subject_pronouns',
      'reading_mcq',
      'short_paragraph',
      ['self introduction', 'name and country', 'job and identity'],
      { min: 60, max: 100 },
      { reading: 3, grammar: 3 },
      '能用 be 动词介绍自己的姓名、国家、身份和简单状态。',
      ['I am ...', 'You are ...', 'He/She is ...', 'Are you ...?'],
      ['主语代词', 'am/is/are', '自我介绍'],
    ),
    createTemplate(
      'A1',
      3,
      'this_that_articles_and_plurals',
      'reading_mcq',
      'short_paragraph',
      ['people and things', 'objects around me', 'simple descriptions'],
      { min: 60, max: 100 },
      { reading: 3, grammar: 3 },
      '能介绍身边的人和物，并正确使用 this/that、a/an 和复数。',
      ['This is a ...', 'That is an ...', 'These are ...', 'They are ...'],
      ['a/an', 'this/that', '名词复数'],
    ),
    createTemplate(
      'A1',
      4,
      'have_has_and_connectors',
      'reading_mcq',
      'short_paragraph',
      ['family and friends', 'relationships', 'appearance and personality'],
      { min: 60, max: 100 },
      { reading: 3, grammar: 3 },
      '能介绍家庭和朋友，并用 have/has 连接简单描述。',
      ['I have ...', 'She has ...', 'He is ... and ...', 'My ... is ...'],
      ['have/has', 'and/but', '人物描述'],
    ),
    createTemplate(
      'A1',
      5,
      'present_simple_routines',
      'reading_mcq',
      'short_paragraph',
      ['daily routine', 'time and weekdays', 'frequency adverbs'],
      { min: 70, max: 110 },
      { reading: 3, grammar: 3 },
      '能描述一天的日常安排，并说明时间和频率。',
      ['I usually ...', 'She often ...', 'I ... at ...', 'On Monday, I ...'],
      ['一般现在时', '第三人称单数', '频率副词'],
    ),
    createTemplate(
      'A1',
      6,
      'countable_uncountable_food_shopping',
      'reading_mcq',
      'short_paragraph',
      ['food and shopping', 'prices and quantities', 'ordering food'],
      { min: 70, max: 110 },
      { reading: 3, grammar: 3 },
      '能在购物或点餐场景中表达数量、价格和需求。',
      ['I would like ...', 'How much is ...?', 'There is some ...', 'There are many ...'],
      ['可数/不可数名词', 'some/any', '价格表达'],
    ),
    createTemplate(
      'A1',
      7,
      'there_is_prepositions_places',
      'reading_mcq',
      'short_paragraph',
      ['places in town', 'directions', 'where is it'],
      { min: 70, max: 110 },
      { reading: 3, grammar: 3 },
      '能说明某个地点在哪里，并进行简单问路。',
      ['There is a ...', 'It is next to ...', 'Where is ...?', 'Go straight.'],
      ['there is/are', '地点介词', '问路表达'],
    ),
    createTemplate(
      'A1',
      8,
      'can_requests_and_help',
      'reading_mcq',
      'short_paragraph',
      ['abilities', 'polite requests', 'appointments and help'],
      { min: 70, max: 110 },
      { reading: 3, grammar: 3 },
      '能表达能力、请求帮助，并约定简单时间。',
      ['I can ...', 'Can you ...?', 'Can I ...?', 'Let us meet at ...'],
      ['can/cannot', '礼貌请求', '约时间'],
    ),
    createTemplate(
      'A1',
      9,
      'simple_past_basic_events',
      'reading_mcq',
      'short_paragraph',
      ['yesterday and weekend', 'was and were', 'short past events'],
      { min: 80, max: 120 },
      { reading: 3, grammar: 3 },
      '能用最基础的过去时讲述昨天或周末发生的事。',
      ['I was ...', 'We were ...', 'I went to ...', 'I had ...'],
      ['was/were', '常见过去式', '过去时间词'],
    ),
    createTemplate(
      'A1',
      10,
      'a1_integrated_review',
      'reading_mcq',
      'short_paragraph',
      ['A1 review', 'shopping directions appointments', 'personal short writing'],
      { min: 80, max: 120 },
      { reading: 3, grammar: 3 },
      '能综合完成 A1 常见生活场景中的介绍、询问、请求和短写作。',
      ['I am ... and I have ...', 'I usually ...', 'There is ...', 'Can I ...?'],
      ['A1 核心句型', '真实场景表达', '短段落写作'],
    ),
  ],
  A2: [
    createTemplate(
      'A2',
      1,
      'past_simple',
      'reading_mcq',
      'short_paragraph',
      ['travel', 'past experience', 'holiday plan'],
      { min: 120, max: 160 },
      { reading: 4, grammar: 4 },
      '能用一般过去时讲述一次旅行、活动或生活经历。',
      ['I visited ... last ...', 'We stayed there for ...', 'It was ... because ...'],
      ['一般过去时', '过去时间词', '经历叙述'],
    ),
    createTemplate(
      'A2',
      2,
      'comparatives',
      'reading_mcq',
      'short_paragraph',
      ['shopping', 'city life', 'technology'],
      { min: 120, max: 160 },
      { reading: 4, grammar: 4 },
      '能比较两个物品、地点或选择，并说明简单理由。',
      ['... is cheaper than ...', 'I prefer ... because ...', 'It is more useful than ...'],
      ['比较级', '选择理由', '购物表达'],
    ),
    createTemplate(
      'A2',
      3,
      'future_plans_going_to',
      'reading_mcq',
      'short_paragraph',
      ['weekend plans', 'study plans', 'travel plans'],
      { min: 120, max: 170 },
      { reading: 4, grammar: 4 },
      '能用 be going to 表达近期计划和安排。',
      ['I am going to ...', 'We are planning to ...', 'I need to ... before ...'],
      ['be going to', '计划表达', '时间顺序'],
    ),
    createTemplate(
      'A2',
      4,
      'modals_advice_should',
      'reading_mcq',
      'short_paragraph',
      ['health advice', 'study advice', 'travel tips'],
      { min: 120, max: 170 },
      { reading: 4, grammar: 4 },
      '能给出简单建议，并解释建议背后的原因。',
      ['You should ...', 'You should not ...', 'It is a good idea to ...'],
      ['should 建议', '原因表达', '健康和学习建议'],
    ),
    createTemplate(
      'A2',
      5,
      'invitations_and_arrangements',
      'reading_mcq',
      'short_paragraph',
      ['invitations', 'meeting friends', 'changing plans'],
      { min: 130, max: 180 },
      { reading: 4, grammar: 4 },
      '能发出邀请、回应邀请，并协商时间地点。',
      ['Would you like to ...?', 'I am free on ...', 'Can we meet at ...?'],
      ['邀请表达', '时间地点安排', '礼貌回应'],
    ),
    createTemplate(
      'A2',
      6,
      'email_requests_and_messages',
      'reading_mcq',
      'short_paragraph',
      ['short email', 'service request', 'school message'],
      { min: 130, max: 180 },
      { reading: 4, grammar: 4 },
      '能写一封简短邮件，清楚说明请求、原因和感谢。',
      ['I am writing to ask about ...', 'Could you please ...?', 'Thank you for your help.'],
      ['邮件格式', '礼貌请求', '说明原因'],
    ),
    createTemplate(
      'A2',
      7,
      'present_continuous_and_now',
      'reading_mcq',
      'short_paragraph',
      ['current activities', 'temporary situations', 'photos'],
      { min: 130, max: 180 },
      { reading: 4, grammar: 4 },
      '能描述正在发生的事情，并区分日常习惯和当前动作。',
      ['I am studying ... now.', 'She usually ..., but today she is ...', 'In the photo, people are ...'],
      ['现在进行时', '习惯与当前动作', '图片描述'],
    ),
    createTemplate(
      'A2',
      8,
      'because_so_and_simple_opinions',
      'reading_mcq',
      'short_paragraph',
      ['likes and dislikes', 'simple opinions', 'daily choices'],
      { min: 140, max: 190 },
      { reading: 4, grammar: 4 },
      '能表达简单观点，并用 because/so 连接理由和结果。',
      ['I think ... because ...', 'I do not like ... because ...', 'It was ..., so I ...'],
      ['because/so', '简单观点', '理由和结果'],
    ),
    createTemplate(
      'A2',
      9,
      'travel_problems_and_solutions',
      'reading_mcq',
      'short_paragraph',
      ['travel problems', 'lost items', 'asking for help'],
      { min: 140, max: 190 },
      { reading: 4, grammar: 4 },
      '能描述一个常见问题，并请求帮助或提出解决办法。',
      ['I have a problem with ...', 'Could you help me ...?', 'First ..., then ...'],
      ['问题描述', '求助表达', '步骤说明'],
    ),
    createTemplate(
      'A2',
      10,
      'a2_integrated_review',
      'reading_mcq',
      'short_paragraph',
      ['A2 review', 'past plans advice email', 'daily life choices'],
      { min: 150, max: 200 },
      { reading: 4, grammar: 4 },
      '能综合完成 A2 日常交流任务：叙述经历、表达计划、给建议和写短邮件。',
      ['Last week, I ...', 'I am going to ...', 'You should ...', 'Could you please ...?'],
      ['A2 核心句型', '日常任务整合', '短邮件写作'],
    ),
  ],
  B1: [
    createTemplate(
      'B1',
      1,
      'present_perfect',
      'reading_mcq',
      'short_paragraph',
      ['work life', 'learning goals', 'health habits'],
      { min: 160, max: 220 },
      { reading: 4, grammar: 4 },
      '能用现在完成时连接过去经历和现在结果。',
      ['I have learned ... since ...', 'I have never ... before.', 'This experience has helped me ...'],
      ['现在完成时', '经历与结果', '学习目标'],
    ),
    createTemplate(
      'B1',
      2,
      'first_conditional',
      'reading_mcq',
      'short_paragraph',
      ['decision making', 'future plan', 'daily challenge'],
      { min: 170, max: 230 },
      { reading: 4, grammar: 4 },
      '能用第一条件句说明可能结果，并提出可行选择。',
      ['If I ..., I will ...', 'Unless we ..., we may ...', 'The best option is ... because ...'],
      ['第一条件句', '选择分析', '结果预测'],
    ),
    createTemplate(
      'B1',
      3,
      'past_continuous_and_story_sequence',
      'reading_mcq',
      'short_paragraph',
      ['personal story', 'unexpected events', 'travel story'],
      { min: 170, max: 230 },
      { reading: 4, grammar: 4 },
      '能讲述一件过去发生的事，并用背景动作和顺序连接叙事。',
      ['I was ... when ...', 'At first ..., then ...', 'In the end, ...'],
      ['过去进行时', '故事顺序', '背景和事件'],
    ),
    createTemplate(
      'B1',
      4,
      'giving_opinions_with_reasons',
      'reading_mcq',
      'short_paragraph',
      ['education opinions', 'work habits', 'technology choices'],
      { min: 180, max: 240 },
      { reading: 4, grammar: 4 },
      '能表达一个清楚观点，并用两个理由支持它。',
      ['In my opinion, ...', 'One reason is that ...', 'Another reason is ...'],
      ['观点段落', '理由展开', '连接词'],
    ),
    createTemplate(
      'B1',
      5,
      'relative_clauses_for_detail',
      'reading_mcq',
      'short_paragraph',
      ['important people', 'useful places', 'favorite tools'],
      { min: 180, max: 240 },
      { reading: 4, grammar: 4 },
      '能用关系从句补充人物、地点或物品的信息。',
      ['A person who ...', 'A place where ...', 'A tool that ...'],
      ['关系从句', '细节补充', '描述扩展'],
    ),
    createTemplate(
      'B1',
      6,
      'reported_speech_basics',
      'reading_mcq',
      'short_paragraph',
      ['news sharing', 'messages', 'work updates'],
      { min: 180, max: 250 },
      { reading: 4, grammar: 4 },
      '能转述别人说的话或消息，并保持时态和人称基本准确。',
      ['She said that ...', 'He told me that ...', 'The message explained that ...'],
      ['间接引语', '转述信息', '工作学习更新'],
    ),
    createTemplate(
      'B1',
      7,
      'problem_solution_paragraph',
      'reading_mcq',
      'short_paragraph',
      ['community problems', 'study problems', 'workplace issues'],
      { min: 190, max: 260 },
      { reading: 4, grammar: 4 },
      '能描述一个问题，分析原因，并提出一个实际解决办法。',
      ['The main problem is ...', 'This happens because ...', 'A practical solution is ...'],
      ['问题解决', '原因分析', '建议段落'],
    ),
    createTemplate(
      'B1',
      8,
      'contrast_and_concession',
      'reading_mcq',
      'short_paragraph',
      ['online learning', 'city and countryside', 'healthy habits'],
      { min: 190, max: 260 },
      { reading: 4, grammar: 4 },
      '能用 however/although 表达对比和让步，让观点更平衡。',
      ['Although ..., ...', 'However, ...', 'On the other hand, ...'],
      ['对比', '让步', '平衡观点'],
    ),
    createTemplate(
      'B1',
      9,
      'formal_requests_and_explanations',
      'reading_mcq',
      'short_paragraph',
      ['formal email', 'course request', 'work request'],
      { min: 190, max: 270 },
      { reading: 4, grammar: 4 },
      '能写较正式的请求邮件，包含背景、请求和后续行动。',
      ['I am writing to request ...', 'The reason is that ...', 'I would appreciate it if ...'],
      ['正式邮件', '请求说明', '礼貌表达'],
    ),
    createTemplate(
      'B1',
      10,
      'b1_integrated_review',
      'reading_mcq',
      'short_paragraph',
      ['B1 review', 'story opinion solution email', 'independent communication'],
      { min: 200, max: 280 },
      { reading: 4, grammar: 4 },
      '能综合完成 B1 独立表达任务：叙事、观点、问题解决和正式请求。',
      ['I have ...', 'If ..., I will ...', 'Although ..., ...', 'A practical solution is ...'],
      ['B1 核心句型', '独立表达', '结构化段落'],
    ),
  ],
  B2: [
    createTemplate(
      'B2',
      1,
      'balanced_arguments_and_concession',
      'reading_mcq',
      'short_paragraph',
      ['social media', 'education choices', 'work flexibility'],
      { min: 220, max: 300 },
      { reading: 4, grammar: 4 },
      '能围绕社会或学习话题写出平衡论证，包含观点、让步和例子。',
      ['While some people argue that ..., I believe ...', 'This is partly because ...', 'However, it is also true that ...'],
      ['平衡论证', '让步表达', '例证展开'],
    ),
    createTemplate(
      'B2',
      2,
      'passive_voice_and_formal_reporting',
      'reading_mcq',
      'short_paragraph',
      ['workplace report', 'public services', 'research summary'],
      { min: 220, max: 300 },
      { reading: 4, grammar: 4 },
      '能用被动语态和正式表达总结事实、过程或报告内容。',
      ['It is believed that ...', 'The results were collected from ...', 'This issue should be addressed by ...'],
      ['被动语态', '正式报告', '事实总结'],
    ),
  ],
  C1: [
    createTemplate(
      'C1',
      1,
      'hedging_and_precise_claims',
      'reading_mcq',
      'short_paragraph',
      ['academic discussion', 'professional decisions', 'policy debate'],
      { min: 260, max: 360 },
      { reading: 4, grammar: 4 },
      '能用 hedging 降低绝对化表达，并提出精准、有分寸的观点。',
      ['It could be argued that ...', 'This appears to suggest ...', 'The evidence is not entirely conclusive.'],
      ['hedging', '精准观点', '学术语域'],
    ),
    createTemplate(
      'C1',
      2,
      'inversion_and_emphasis',
      'reading_mcq',
      'short_paragraph',
      ['leadership', 'innovation', 'complex problem solving'],
      { min: 260, max: 360 },
      { reading: 4, grammar: 4 },
      '能使用倒装和强调结构，让高阶表达更有节奏和重点。',
      ['Rarely have we seen ...', 'Not only does this ..., but it also ...', 'What matters most is ...'],
      ['倒装', '强调结构', '高级衔接'],
    ),
  ],
  C2: [
    createTemplate(
      'C2',
      1,
      'rhetorical_devices_and_persuasive_style',
      'reading_mcq',
      'short_paragraph',
      ['editorial writing', 'public speech', 'expert commentary'],
      { min: 300, max: 420 },
      { reading: 4, grammar: 4 },
      '能用修辞、语气和节奏控制写出有说服力的高阶文本。',
      ['The question is not whether ..., but how ...', 'Far from being ..., it is ...', 'This is no minor detail; it is ...'],
      ['修辞策略', '说服性写作', '语气控制'],
    ),
    createTemplate(
      'C2',
      2,
      'style_shift_and_editorial_revision',
      'reading_mcq',
      'short_paragraph',
      ['style editing', 'professional communication', 'text transformation'],
      { min: 300, max: 420 },
      { reading: 4, grammar: 4 },
      '能在正式、简洁、批判或亲和等语域之间灵活转换并润色文本。',
      ['The original version sounds ..., whereas the revised version ...', 'A more concise alternative would be ...', 'The tone can be adjusted by ...'],
      ['风格转换', '文本润色', '专家级表达'],
    ),
  ],
}

export const allLessonTemplates = Object.values(lessonTemplatesByLevel).flat()
