import type { CefrLevel, LessonTemplate } from './types'

const createTemplate = (
  level: CefrLevel,
  sequence: number,
  grammarFocus: string,
  readingTaskType: LessonTemplate['readingTaskType'],
  writingTaskType: LessonTemplate['writingTaskType'],
  themePool: string[],
  targetWordRange: LessonTemplate['targetWordRange'],
  questionCounts: LessonTemplate['questionCounts'],
): LessonTemplate => ({
  templateId: `${level}-${String(sequence).padStart(2, '0')}`,
  level,
  sequence,
  grammarFocus,
  readingTaskType,
  writingTaskType,
  themePool,
  targetWordRange,
  questionCounts,
})

export const lessonTemplatesByLevel: Record<CefrLevel, LessonTemplate[]> = {
  A1: [
    createTemplate(
      'A1',
      1,
      'alphabet_and_classroom_english',
      'reading_mcq',
      'short_paragraph',
      ['letters and sounds', 'classroom English', 'numbers and dates'],
      { min: 60, max: 100 },
      { reading: 3, grammar: 3 },
    ),
    createTemplate(
      'A1',
      2,
      'be_and_subject_pronouns',
      'reading_mcq',
      'short_paragraph',
      ['self introduction', 'name and country', 'job and identity'],
      { min: 60, max: 100 },
      { reading: 3, grammar: 3 },
    ),
    createTemplate(
      'A1',
      3,
      'this_that_articles_and_plurals',
      'reading_mcq',
      'short_paragraph',
      ['people and things', 'objects around me', 'simple descriptions'],
      { min: 60, max: 100 },
      { reading: 3, grammar: 3 },
    ),
    createTemplate(
      'A1',
      4,
      'have_has_and_connectors',
      'reading_mcq',
      'short_paragraph',
      ['family and friends', 'relationships', 'appearance and personality'],
      { min: 60, max: 100 },
      { reading: 3, grammar: 3 },
    ),
    createTemplate(
      'A1',
      5,
      'present_simple_routines',
      'reading_mcq',
      'short_paragraph',
      ['daily routine', 'time and weekdays', 'frequency adverbs'],
      { min: 70, max: 110 },
      { reading: 3, grammar: 3 },
    ),
    createTemplate(
      'A1',
      6,
      'countable_uncountable_food_shopping',
      'reading_mcq',
      'short_paragraph',
      ['food and shopping', 'prices and quantities', 'ordering food'],
      { min: 70, max: 110 },
      { reading: 3, grammar: 3 },
    ),
    createTemplate(
      'A1',
      7,
      'there_is_prepositions_places',
      'reading_mcq',
      'short_paragraph',
      ['places in town', 'directions', 'where is it'],
      { min: 70, max: 110 },
      { reading: 3, grammar: 3 },
    ),
    createTemplate(
      'A1',
      8,
      'can_requests_and_help',
      'reading_mcq',
      'short_paragraph',
      ['abilities', 'polite requests', 'appointments and help'],
      { min: 70, max: 110 },
      { reading: 3, grammar: 3 },
    ),
    createTemplate(
      'A1',
      9,
      'simple_past_basic_events',
      'reading_mcq',
      'short_paragraph',
      ['yesterday and weekend', 'was and were', 'short past events'],
      { min: 80, max: 120 },
      { reading: 3, grammar: 3 },
    ),
    createTemplate(
      'A1',
      10,
      'a1_integrated_review',
      'reading_mcq',
      'short_paragraph',
      ['A1 review', 'shopping directions appointments', 'personal short writing'],
      { min: 80, max: 120 },
      { reading: 3, grammar: 3 },
    ),
  ],
  A2: [
    createTemplate(
      'A2',
      1,
      'past_simple',
      'reading_mcq',
      'short_paragraph',
      ['travel', 'past experience', 'holiday plan'],
      { min: 120, max: 160 },
      { reading: 4, grammar: 4 },
    ),
    createTemplate(
      'A2',
      2,
      'comparatives',
      'reading_mcq',
      'short_paragraph',
      ['shopping', 'city life', 'technology'],
      { min: 120, max: 160 },
      { reading: 4, grammar: 4 },
    ),
  ],
  B1: [
    createTemplate(
      'B1',
      1,
      'present_perfect',
      'reading_mcq',
      'short_paragraph',
      ['work life', 'learning goals', 'health habits'],
      { min: 160, max: 220 },
      { reading: 4, grammar: 4 },
    ),
    createTemplate(
      'B1',
      2,
      'first_conditional',
      'reading_mcq',
      'short_paragraph',
      ['decision making', 'future plan', 'daily challenge'],
      { min: 170, max: 230 },
      { reading: 4, grammar: 4 },
    ),
  ],
}

export const allLessonTemplates = Object.values(lessonTemplatesByLevel).flat()
