import type { CefrLevel, LessonTemplate } from './types'

const createTemplate = (
  level: CefrLevel,
  sequence: number,
  grammarFocus: string,
  readingTaskType: LessonTemplate['readingTaskType'],
  writingTaskType: LessonTemplate['writingTaskType'],
  themePool: string[],
  targetWordRange: LessonTemplate['targetWordRange'],
  questionCounts: LessonTemplate['questionCounts'],
  teachingGoal?: string,
  targetSentences: string[] = [],
  reviewFocus: string[] = [],
): LessonTemplate => ({
  templateId: `${level}-${String(sequence).padStart(2, '0')}`,
  level,
  sequence,
  grammarFocus,
  readingTaskType,
  writingTaskType,
  themePool,
  teachingGoal,
  targetSentences,
  reviewFocus,
  targetWordRange,
  questionCounts,
})

export const lessonTemplatesByLevel: Record<CefrLevel, LessonTemplate[]> = {
  A1: [
    createTemplate(
      'A1',
      1,
      'alphabet_and_classroom_english',
      'reading_mcq',
      'short_paragraph',
      ['letters and sounds', 'classroom English', 'numbers and dates'],
      { min: 60, max: 100 },
      { reading: 3, grammar: 3 },
      '能听懂并说出课堂里最常用的英文指令、数字和日期。',
      ['How do you spell ...?', 'Can you repeat that?', 'It is number ...'],
      ['字母发音', '数字和日期', '课堂指令'],
    ),
    createTemplate(
      'A1',
      2,
      'be_and_subject_pronouns',
      'reading_mcq',
      'short_paragraph',
      ['self introduction', 'name and country', 'job and identity'],
      { min: 60, max: 100 },
      { reading: 3, grammar: 3 },
      '能用 be 动词介绍自己的姓名、国家、身份和简单状态。',
      ['I am ...', 'You are ...', 'He/She is ...', 'Are you ...?'],
      ['主语代词', 'am/is/are', '自我介绍'],
    ),
    createTemplate(
      'A1',
      3,
      'this_that_articles_and_plurals',
      'reading_mcq',
      'short_paragraph',
      ['people and things', 'objects around me', 'simple descriptions'],
      { min: 60, max: 100 },
      { reading: 3, grammar: 3 },
      '能介绍身边的人和物，并正确使用 this/that、a/an 和复数。',
      ['This is a ...', 'That is an ...', 'These are ...', 'They are ...'],
      ['a/an', 'this/that', '名词复数'],
    ),
    createTemplate(
      'A1',
      4,
      'have_has_and_connectors',
      'reading_mcq',
      'short_paragraph',
      ['family and friends', 'relationships', 'appearance and personality'],
      { min: 60, max: 100 },
      { reading: 3, grammar: 3 },
      '能介绍家庭和朋友，并用 have/has 连接简单描述。',
      ['I have ...', 'She has ...', 'He is ... and ...', 'My ... is ...'],
      ['have/has', 'and/but', '人物描述'],
    ),
    createTemplate(
      'A1',
      5,
      'present_simple_routines',
      'reading_mcq',
      'short_paragraph',
      ['daily routine', 'time and weekdays', 'frequency adverbs'],
      { min: 70, max: 110 },
      { reading: 3, grammar: 3 },
      '能描述一天的日常安排，并说明时间和频率。',
      ['I usually ...', 'She often ...', 'I ... at ...', 'On Monday, I ...'],
      ['一般现在时', '第三人称单数', '频率副词'],
    ),
    createTemplate(
      'A1',
      6,
      'countable_uncountable_food_shopping',
      'reading_mcq',
      'short_paragraph',
      ['food and shopping', 'prices and quantities', 'ordering food'],
      { min: 70, max: 110 },
      { reading: 3, grammar: 3 },
      '能在购物或点餐场景中表达数量、价格和需求。',
      ['I would like ...', 'How much is ...?', 'There is some ...', 'There are many ...'],
      ['可数/不可数名词', 'some/any', '价格表达'],
    ),
    createTemplate(
      'A1',
      7,
      'there_is_prepositions_places',
      'reading_mcq',
      'short_paragraph',
      ['places in town', 'directions', 'where is it'],
      { min: 70, max: 110 },
      { reading: 3, grammar: 3 },
      '能说明某个地点在哪里，并进行简单问路。',
      ['There is a ...', 'It is next to ...', 'Where is ...?', 'Go straight.'],
      ['there is/are', '地点介词', '问路表达'],
    ),
    createTemplate(
      'A1',
      8,
      'can_requests_and_help',
      'reading_mcq',
      'short_paragraph',
      ['abilities', 'polite requests', 'appointments and help'],
      { min: 70, max: 110 },
      { reading: 3, grammar: 3 },
      '能表达能力、请求帮助，并约定简单时间。',
      ['I can ...', 'Can you ...?', 'Can I ...?', 'Let us meet at ...'],
      ['can/cannot', '礼貌请求', '约时间'],
    ),
    createTemplate(
      'A1',
      9,
      'simple_past_basic_events',
      'reading_mcq',
      'short_paragraph',
      ['yesterday and weekend', 'was and were', 'short past events'],
      { min: 80, max: 120 },
      { reading: 3, grammar: 3 },
      '能用最基础的过去时讲述昨天或周末发生的事。',
      ['I was ...', 'We were ...', 'I went to ...', 'I had ...'],
      ['was/were', '常见过去式', '过去时间词'],
    ),
    createTemplate(
      'A1',
      10,
      'a1_integrated_review',
      'reading_mcq',
      'short_paragraph',
      ['A1 review', 'shopping directions appointments', 'personal short writing'],
      { min: 80, max: 120 },
      { reading: 3, grammar: 3 },
      '能综合完成 A1 常见生活场景中的介绍、询问、请求和短写作。',
      ['I am ... and I have ...', 'I usually ...', 'There is ...', 'Can I ...?'],
      ['A1 核心句型', '真实场景表达', '短段落写作'],
    ),
  ],
  A2: [
    createTemplate(
      'A2',
      1,
      'past_simple',
      'reading_mcq',
      'short_paragraph',
      ['travel', 'past experience', 'holiday plan'],
      { min: 120, max: 160 },
      { reading: 4, grammar: 4 },
    ),
    createTemplate(
      'A2',
      2,
      'comparatives',
      'reading_mcq',
      'short_paragraph',
      ['shopping', 'city life', 'technology'],
      { min: 120, max: 160 },
      { reading: 4, grammar: 4 },
    ),
  ],
  B1: [
    createTemplate(
      'B1',
      1,
      'present_perfect',
      'reading_mcq',
      'short_paragraph',
      ['work life', 'learning goals', 'health habits'],
      { min: 160, max: 220 },
      { reading: 4, grammar: 4 },
    ),
    createTemplate(
      'B1',
      2,
      'first_conditional',
      'reading_mcq',
      'short_paragraph',
      ['decision making', 'future plan', 'daily challenge'],
      { min: 170, max: 230 },
      { reading: 4, grammar: 4 },
    ),
  ],
}

export const allLessonTemplates = Object.values(lessonTemplatesByLevel).flat()
